# -*- coding: utf-8 -*-
"""ExamenFinal_Analisis_Financiero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuOMQOXtZw2pe-HsBo6W34tbW2MIY-OX

# 📊 Examen Final: Dataset de Kaggle + Análisis Financiero en Colab
Este notebook contiene las instrucciones para que desarrollar el examen final.

## ⭐ PASO 1 — Buscar un dataset en Kaggle
1. Entra a https://www.kaggle.com/datasets
2. Busca un dataset financiero (acciones, criptomonedas, oro, petróleo, etc.)
3. Descárgalo a tu computador (formato CSV).

## ⭐ PASO 2 — Subir el dataset a Colab
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# TODO: cambia el nombre del archivo al que subiste
# df = pd.read_csv('archivo.csv')
# df.head()

"""## ⭐ PASO 3 — Limpieza y preparación del dataset
- Revisa tipos de datos
- Convierte fechas
- Ordena por fecha
- Maneja valores nulos
"""

# TODO: escribir aquí tu proceso de limpieza

"""## ⭐ PASO 4 — Análisis financiero básico
Calcula:
- Rendimiento diario
- Rendimiento promedio
- Volatilidad
- Máx y mín históricos
"""

# TODO: calcular métricas financieras

"""## ⭐ PASO 5 — Gráficos obligatorios
- Serie de precios
- Rendimientos
- Volumen (si aplica)
"""

import matplotlib.pyplot as plt

# TODO: generar gráficos

"""## ⭐ PASO 6 — Preguntas de análisis
1. ¿El activo es volátil? ¿Por qué?
2. ¿Tiene tendencia clara?
3. ¿Hay eventos con movimientos fuertes?
4. ¿Es buena inversión a corto/largo plazo?
5. ¿Limitaciones del dataset?

Escribe tus respuestas abajo.

## ⭐ PASO 7 — Conclusiones
Redacta mínimo 5 conclusiones basadas en tu análisis.
"""